signature:
  key: "5HtbQzoofDVmEvzAMd89iq5nRpFUm8xudgkSNZ4rPN9z5AWcGEJ"

google:
  secret_path: "./token.json"
  qrPath: ""
  password: "Markys1256"
  login: "mark.cherepovskyi@nure.ua"
  apiKey: "AIzaSyBWT-h4KRDnjmzEV2lFrXz8Nil1ECHxZy8"

tables:
  result: ""
  input: "certificates.xlsx"
