signature:
  key: "5HtbQzoofDVmEvzAMd89iq5nRpFUm8xudgkSNZ4rPN9z5AWcGEJ"

google:
  secret_path: "./client_secret.json"
  qr_path: "qr"
  api_key: "AIzaSyAX5pLvCS9GQ23YFWvfpH__4nXo4BuqBUM"
  code: "4/0AWgavddEukwpUxaJ8CJBugnCbCf2bzTk4CakxD8IJndksk6EN_K9na94pP-UxT03AR1wnA"


tables:
  result: "test3s.xlsx"
  input: "certificates.xlsx"

qr_code:
  qr_path: "./qr/"
  template: "message:\n%s\n\naddress:\n%s\n\nsignature:\n%s\n\ncertificate page:\nhttps://dlt-academy.com/certificates"

templates:
  list:
    - params:
        golang: "Golang programming on fundamental aspects"
    - params:
        distributed_system: "Blockchain and Distributed Systems"
    - params:
        decentralize_technologies: "Basic Level in Decentralized Technologies"
    - params:
        bitcoin: "Біткоїн та криптовалюти"
    - params:
        security: "Cryptography and information security theory"
    - params:
        database: "Theory of database organization and basic SQL"
    - params:
        blockchain: "Beginner at theoretical aspects blockchain technology"


