log:
  disable_sentry: true
  level: info

listener:
  addr: :7898

signature:
  key: "5HtbQzoofDVmEvzAMd89iq5nRpFUm8xudgkSNZ4rPN9z5AWcGEJ"


networks:
  rpc_eth: "https://goerli.infura.io/v3/45efc27205e746adb3a1d6c3da69a7ba"
  ipfs: "https://ipfs.infura.io:5001"
  ipfs_pr_id: "2LgGs3QZ5Ndz065ZVu4xoSTWzcU"
  ipfs_pr_key: "4afcd5182cb6e849fa72726d44f77186"


google:
  secret_path: "./client.json"
  qr_path: "qr"
  pdf_path: "pdf"
  api_key: "AIzaSyB5JPdmDD-BCyOs7WpQaXqz_wiZJ-VMQ-c"
  code: "4/0AWtgzh5cAb2ZYTXGSsf6OQlOftLQryfNTxkgrDoKiLq7bpr9HTOUy55wYwTxC_7w32Na_Q"
  enable: true

tables:
  result: "test.xlsx"
  input: "certificates.xlsx"

qr_code:
  qr_path: "./qr/"
  template: "message:\n%s\n\naddress:\n%s\n\nsignature:\n%s\n\ncertificate page:\nhttps://dlt-academy.com/certificates"

templates:
  list:
    golang: "Golang programming on fundamental aspects"
    distributed_system: "Blockchain and Distributed Systems"
    cryptocurrencies: "Cryptocurrencies and Distributed Systems"
    decentralize_technologies: "Basic Level in Decentralized Technologies"
    bitcoin: "Біткоїн та криптовалюти"
    security: "Cryptography and information security theory"
    database: "Theory of database organization and basic SQL"
    blockchain: "Beginner at theoretical aspects blockchain technology"
    solidity: ""


cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: css
  service_port: 80

