signature:
  key: "5HtbQzoofDVmEvzAMd89iq5nRpFUm8xudgkSNZ4rPN9z5AWcGEJ"

google:
  secret_path: "./client_secret.json"
  qrPath: ""
  password: "Markys1256"
  login: "mark.cherepovskyi@nure.ua"
  apiKey: "AIzaSyAX5pLvCS9GQ23YFWvfpH__4nXo4BuqBUM"
  code: "4/0AWgavdeOIwqKrlCilWD_6ZN9kpg0ao6B6IZ44RWn-Iw58kMtL1_5vQh1KguHp2YsWisDsA"

tables:
  result: ""
  input: "certificates.xlsx"
