log:
  disable_sentry: true
  level: info

listener:
  addr: :7898

signature:
  key: "5HtbQzoofDVmEvzAMd89iq5nRpFUm8xudgkSNZ4rPN9z5AWcGEJ"

google:
  secret_path: "./client.json"
  qr_path: "qr"
  api_key: "AIzaSyB5JPdmDD-BCyOs7WpQaXqz_wiZJ-VMQ-c"
  code: "4/0AWtgzh5cAb2ZYTXGSsf6OQlOftLQryfNTxkgrDoKiLq7bpr9HTOUy55wYwTxC_7w32Na_Q"
  enable: true

tables:
  result: "test.xlsx"
  input: "certificates.xlsx"

qr_code:
  qr_path: "./qr/"
  template: "message:\n%s\n\naddress:\n%s\n\nsignature:\n%s\n\ncertificate page:\nhttps://dlt-academy.com/certificates"

templates:
  list:
    golang: "Golang programming on fundamental aspects"
    distributed_system: "Blockchain and Distributed Systems"
    cryptocurrencies: "Cryptocurrencies and Distributed Systems"
    decentralize_technologies: "Basic Level in Decentralized Technologies"
    bitcoin: "Біткоїн та криптовалюти"
    security: "Cryptography and information security theory"
    database: "Theory of database organization and basic SQL"
    blockchain: "Beginner at theoretical aspects blockchain technology"

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: css
  service_port: 80

