signature:
  key: "5HtbQzoofDVmEvzAMd89iq5nRpFUm8xudgkSNZ4rPN9z5AWcGEJ"

google:
  secret_path: "./client_secret.json"
  qr_path: ""
  api_key: "AIzaSyAX5pLvCS9GQ23YFWvfpH__4nXo4BuqBUM"
  code: "4/0AWgavdctATOMYsPFyMqsJvO7yhtIS92lMI9AUbWulvZatn2DKkso9-tbz9RU1XpqM9FyGA"

tables:
  result: "test.xlsx"
  input: "certificates.xlsx"
