FROM golang:1.19 as buildbase
# Ignore APT warnings about not having a TTY
ENV DEBIAN_FRONTEND noninteractive



# Copy source code
# install build essentials
RUN apt-get update && \
    apt-get install -y wget build-essential  libc-dev  pkg-config --no-install-recommends

# Install ImageMagick deps
RUN apt-get -q -y install libjpeg-dev libpng-dev libtiff-dev \
    libgif-dev libx11-dev --no-install-recommends

ENV IMAGEMAGICK_VERSION=6.9.10-11

RUN cd && \
	wget https://github.com/ImageMagick/ImageMagick6/archive/${IMAGEMAGICK_VERSION}.tar.gz && \
	tar xvzf ${IMAGEMAGICK_VERSION}.tar.gz && \
	cd ImageMagick* && \
	./configure \
	    --without-magick-plus-plus \
	    --without-perl \
	    --disable-openmp \
	    --with-gvc=no \
	    --disable-docs && \
	make -j$(nproc) && make install && \
	ldconfig /usr/local/lib



# Build the Go application
WORKDIR /go/src/github.com/Digital-Certificates-DL/certificates-svc

COPY . .
RUN ls /go/src/github.com/Digital-Certificates-DL/
RUN ls /go/src/github.com/Digital-Certificates-DL/certificates-svc
RUN  go install
RUN go build -o /usr/local/bin /go/src/github.com/Digital-Certificates-DL/certificates-svc
RUN  ls

FROM debian:latest

COPY

ENTRYPOINT  ["/usr/local/bin/ccp"]
